services:
  grpc-server:
    build: ./GRPC-SERVER
    container_name: grpc-server
    ports:
      - "50051:50051"
    volumes:
      - grpc-server:/app/media
    environment:
      - GRPC_SERVER_PORT=50051
      - MAX_WORKERS=10
      - MEDIA_PATH=/app/media
      - DBNAME=mydatabase
      - DBUSERNAME=myuser
      - DBPASSWORD=mypassword
      - DBHOST=db
      - DBPORT=5432
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=user
      - RABBITMQ_PW=password
    depends_on:
      - db

  rest_api_server:
    build: ./rest_api_server
    container_name: rest_api_server
    ports:
      - "8000:8000"
    environment:
      - GRPC_PORT=50051
      - GRPC_HOST=grpc-server
      - DBNAME=mydatabase
      - DBUSERNAME=myuser
      - DBPASSWORD=mypassword
      - DBHOST=db
      - DBPORT=5432
    depends_on:
      - db
      - grpc-server

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672" # Default RabbitMQ port
      - "15672:15672" # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  worker:
    build: ./worker-rabbit-csv
    ports: 
      - "8003:8003"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=user
      - RABBITMQ_PW=password
      - DBNAME=mydatabase
      - DBUSERNAME=myuser
      - DBPASSWORD=mypassword
      - DBHOST=db
      - DBPORT=5432
    depends_on:
      - rabbitmq
      - db
      - grpc-server

volumes:
  grpc-server:
  pgdata:
