services:
  grpc-server:
    build: ./grpc-server
    container_name: grpc-server
    ports:
      - "50051:50051"
    volumes:
      - grpc-server:/app/media
    environment:
      - GRPC_SERVER_PORT=50051
      - MAX_WORKERS=10
      - MEDIA_PATH=/app/media
      - DBNAME=mydatabase
      - DBUSER=myuser
      - DBPASSWORD=mypassword
      - DBHOST=db
      - DBPORT=5432
    depends_on:
      - db

  rest-api-server:
    build: ./rest_api_server
    container_name: rest_api_server
    ports:
      - "8000:8000"
    environment:
      - GRPC_HOST=grpc-server
      - GRPC_PORT=50051
      - DBNAME=mydatabase
      - DBUSER=myuser
      - DBPASSWORD=mypassword
      - DBHOST=db
      - DBPORT=5432
    depends_on:
      - db
      - grpc-server
      
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  grpc-server:
  pgdata: 