# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server_Services.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'server_Services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15server_Services.proto\x12\x0fserver_services\".\n\x0b\x46ileRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\"\'\n\x10\x43svToXmlResponse\x12\x13\n\x0bxml_content\x18\x01 \x01(\t\"8\n\rSubXmlRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x05\x12\x16\n\x0ewarehouse_name\x18\x02 \x01(\t\"(\n\x0eSubXmlResponse\x12\x16\n\x0esubxml_content\x18\x01 \x01(\t2\xb9\x01\n\x15\x46ileProcessingService\x12R\n\x0f\x43onvertCsvToXml\x12\x1c.server_services.FileRequest\x1a!.server_services.CsvToXmlResponse\x12L\n\tGetSubXml\x12\x1e.server_services.SubXmlRequest\x1a\x1f.server_services.SubXmlResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_Services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=42
  _globals['_FILEREQUEST']._serialized_end=88
  _globals['_CSVTOXMLRESPONSE']._serialized_start=90
  _globals['_CSVTOXMLRESPONSE']._serialized_end=129
  _globals['_SUBXMLREQUEST']._serialized_start=131
  _globals['_SUBXMLREQUEST']._serialized_end=187
  _globals['_SUBXMLRESPONSE']._serialized_start=189
  _globals['_SUBXMLRESPONSE']._serialized_end=229
  _globals['_FILEPROCESSINGSERVICE']._serialized_start=232
  _globals['_FILEPROCESSINGSERVICE']._serialized_end=417
# @@protoc_insertion_point(module_scope)
