# Generated by Django 5.1.3 on 2025-01-22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("age", models.IntegerField()),
                ("height_cm", models.IntegerField()),
                ("weight_kgs", models.DecimalField(decimal_places=2, max_digits=5)),
                ("positions", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=100)),
                ("overall_rating", models.IntegerField()),
                ("potential", models.IntegerField()),
                ("value_euro", models.DecimalField(decimal_places=2, max_digits=12)),
                ("wage_euro", models.DecimalField(decimal_places=2, max_digits=12)),
                ("preferred_foot", models.CharField(max_length=10)),
                ("international_reputation", models.IntegerField()),
                ("weak_foot", models.IntegerField()),
                ("skill_moves", models.IntegerField()),
                ("body_type", models.CharField(max_length=50)),
                ("release_clause_euro", models.DecimalField(decimal_places=2, max_digits=12)),
                ("national_team", models.CharField(max_length=100)),
                ("national_rating", models.IntegerField()),
                ("national_team_position", models.CharField(max_length=50)),
                ("national_jersey_number", models.IntegerField()),
                ("crossing", models.IntegerField()),
                ("finishing", models.IntegerField()),
                ("heading_accuracy", models.IntegerField()),
                ("short_passing", models.IntegerField()),
                ("volleys", models.IntegerField()),
                ("dribbling", models.IntegerField()),
                ("curve", models.IntegerField()),
                ("freekick_accuracy", models.IntegerField()),
                ("long_passing", models.IntegerField()),
                ("ball_control", models.IntegerField()),
                ("acceleration", models.IntegerField()),
                ("sprint_speed", models.IntegerField()),
                ("agility", models.IntegerField()),
                ("reactions", models.IntegerField()),
                ("balance", models.IntegerField()),
                ("shot_power", models.IntegerField()),
                ("jumping", models.IntegerField()),
                ("stamina", models.IntegerField()),
                ("strength", models.IntegerField()),
                ("long_shots", models.IntegerField()),
                ("aggression", models.IntegerField()),
                ("interceptions", models.IntegerField()),
                ("positioning", models.IntegerField()),
                ("vision", models.IntegerField()),
                ("penalties", models.IntegerField()),
                ("composure", models.IntegerField()),
                ("marking", models.IntegerField()),
                ("standing_tackle", models.IntegerField()),
                ("sliding_tackle", models.IntegerField()),
            ],
            options={
                "db_table": "players",
            },
        ),
    ]
